### Update an existing word
PATCH http://localhost:{{port}}/words/9
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "wordForeign": "XD",
  "learningStatus": "reviewing",
  "id": 59,
  "userId": 3
}

### Create a new word
POST http://localhost:3000/words
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "dictionaryId": 55,
  "wordForeign": "foreign",
  "wordTranslation": "translation"
}

### ID specific
GET http://localhost:3000/words/9
Accept: application/json
Authorization: Bearer {{user1_token}}

###

### ALL
GET http://localhost:3000/words
Accept: application/json
Authorization: Bearer {{user1_token}}

###
