### Remove word
DELETE http://localhost:{{port}}/words/20
Content-Type: application/json
Authorization: Bearer {{user1_token}}

### Update an existing word
PATCH http://localhost:{{port}}/words/17
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "wordForeign": "XsiemaDdsddss",
  "learningStatus": "reviewing",
  "id": 59,
  "userId": 3
}

### Create a new word
POST http://localhost:3000/words
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "dictionaryId": 60,
  "wordForeign": "4",
  "wordTranslation": "translation"
}

### ID specific
GET http://localhost:3000/words/9
Accept: application/json
Authorization: Bearer {{user1_token}}

###

### ALL
GET http://localhost:3000/words
Accept: application/json
Authorization: Bearer {{user1_token}}

###
