GET http://localhost:3000/authentication/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTY0NjU5MDEzOCwiZXhwIjoxNjU0MzY2MTM4fQ.WlBOcrpTYPOBaDTjp3UXZm5jZBO6W8JOY1YIqIkRZis

###

POST http://localhost:3000/authentication/register
Content-Type: application/json

{
  "email": "{{user2}}",
  "password": "{{password}}",
  "themeMode": "Dark"
}

###
POST http://localhost:3000/authentication/login
Content-Type: application/json

{
  "email": "{{user1}}",
  "password": "{{password}}"
}

###
