GET http://localhost:3000/authentication/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTY0NTk3ODk5MSwiZXhwIjoxNjQ2MDY1MzkxfQ.Yr9cAyQAHuYFfr-3LaqpWrAJE8mOAcZtlR4HO2Lmu_g

###

POST http://localhost:3000/authentication/register
Content-Type: application/json

{
  "email": "{{user2}}a",
  "password": "{{password}}",
  "themeMode": "Dark"
}

###
POST http://localhost:3000/authentication/login
Content-Type: application/json

{
  "email": "{{user1}}",
  "password": "{{password}}"
}

###
