###
PATCH http://localhost:{{port}}/dictionary/4
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "language": "sssssa"
}

###
GET http://localhost:{{port}}/dictionary/27
Accept: application/json
Authorization: Bearer {{user2_token}}

###

###
POST http://localhost:{{port}}/dictionary
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "language": "sssssa"
}

###
GET http://localhost:{{port}}/dictionary
Accept: application/json
Authorization: Bearer {{user1_token}}

###
