###
DELETE http://localhost:{{port}}/dictionary/63
Content-Type: application/json
Authorization: Bearer {{user1_token}}

###
PATCH http://localhost:{{port}}/dictionary/57
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "language": "updatedd",
  "flashcardId": 19
}

### Get single dictionary with words
GET http://localhost:{{port}}/dictionary/55/words
Accept: application/json
Authorization: Bearer {{user1_token}}

### Get single dictionary with no words
GET http://localhost:{{port}}/dictionary/57
Accept: application/json
Authorization: Bearer {{user1_token}}

###

###
POST http://localhost:{{port}}/dictionary
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "language": "otheruserr"
}

###
GET http://localhost:{{port}}/dictionary
Accept: application/json
Authorization: Bearer {{user1_token}}

###
