###
DELETE http://localhost:{{port}}/dictionary/55
Content-Type: application/json
Authorization: Bearer {{user1_token}}

###
PATCH http://localhost:{{port}}/dictionary/52
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "language": "updatedd"
}

### Get single dictionary with words
GET http://localhost:{{port}}/dictionary/55/words
Accept: application/json
Authorization: Bearer {{user1_token}}

### Get single dictionary with no words
GET http://localhost:{{port}}/dictionary/55
Accept: application/json
Authorization: Bearer {{user1_token}}

###

###
POST http://localhost:{{port}}/dictionary
Content-Type: application/json
Authorization: Bearer {{user1_token}}

{
  "language": "updateddd"
}

###
GET http://localhost:{{port}}/dictionary
Accept: application/json
Authorization: Bearer {{user1_token}}

###
